USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SCD2_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE STORAGE INTEGRATION SCD2_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<aws-account-id>:role/scd2-snowflake-s3-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://scd2-product-data-jenny/raw_data/');

DESC INTEGRATION SCD2_INT;

CREATE OR REPLACE FILE FORMAT SCD2_DB.BRONZE.SCD2_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE SCD2_DB.BRONZE.SCD2_STAGE
  STORAGE_INTEGRATION = SCD2_INT
  URL = 's3://scd2-product-data-jenny/raw_data/'
  FILE_FORMAT = SCD2_DB.BRONZE.SCD2_CSV_FORMAT;

LS @SCD2_DB.BRONZE.SCD2_STAGE;
